### ISSUE TITLE
Add route to result from problem solved with OSRM

### ISSUE THREAD

**Issue by frodrigo** [jcoupey/vroom#12]
Add `route` to JSON result from problem solved with OSRM. Rematching the lat/lon number truncated with the initial input data is not so simple. Please can you output the `route` attribut as well, something like in the TSP loader.

```
    route += "\"tour\":[";
    for(auto const& step: tour){
      // Using rank rather than index to describe places.
      route += std::to_string(step + 1) + ",";
    }
    route.pop_back();          // Remove trailing comma.
    route += "],";
```

**Comment by jcoupey** [comment]
A `route` key is always present in problems solved with OSRM, I guess you are thinking about the `tour` key which is present only for tsplib file so far? (describing the ordered solution with regard to the index of the locations in the input)

I've already added this for my latest experiments to easily match input locations so it should be pushed soon.

**Comment by frodrigo** [comment]
Yes the `tour`. Ok thank.

**Comment by jcoupey** [comment]
Note that when using OSRM (i.e. without the -t flag), input locations are numbered from 0 in the `tour` description. 

The TSPLIB parser uses any index provided in the NODE_COORD_SECTION (usually numbering from 1).
