### ISSUE TITLE
Open tour - no loop

### ISSUE THREAD

**Issue by frodrigo** [jcoupey/vroom#15]
Do you plan to support open tour ?
- with different fixed start and stop
- more general case, with fixed or not start and stop

**Comment by jcoupey** [comment]
First try at forcing either start or end of tour to produce an "open" trip which is not a loop (nothing implemented yet to force both start and end).

Option `-s ` (resp. `-e`) will force the first (resp. last) input location to be set as start (resp. end), the end (resp. start) of the trip being chosen during the optimization process.

What you expect to happen when using both `-s` and `-e` is not implemented (yet).

Should be ok for both TSPLIB files and when using OSRM. Solution cost and route geometry should be set accordingly.

**Comment by jcoupey** [comment]
Using both `-s` and `-e` to force start and end of an open route should be ok now.

The whole feature would benefit from more real-life testing... So glad to have any feedback whenever possible.
