### ISSUE TITLE
Load matrix

### ISSUE THREAD

**Issue by frodrigo** [jcoupey/vroom#2]
Do you plan to load arbitrary matrix or TSPLIB file format ?

**Comment by jcoupey** [comment]
Hi

Loading an arbitrary matrix is not a problem with the code as it is, but it's not available from command-line yet.

The best way to expose this functionality would indeed be to support TSPLIB formats. It's definitely something that should happen.

**Comment by jcoupey** [comment]
Available feature as of v0.2.
