### ISSUE TITLE
Assertion `infos.HasMember("route_summary")' failed

### ISSUE THREAD

**Issue by KieCap** [jcoupey/vroom#28]
Using OSRM v4.9.1 and current master of VROOM.

We're getting the following error when passing ~950 points, along with -s and -g options.

```
vroom: structures/../loaders/osrm_wrapper.h:259: virtual void osrm_wrapper::get_route_infos(const std::list<short unsigned int>&, rapidjson::Document&) const: Assertion `infos.HasMember("route_summary")' failed. 
```

OSRM is running with --max-table-size and --max-matching-size set to 9999.

We don't have any issues when using a smaller number of points, so I'm wondering is there some option get need to set when running osrm-routed?

Thanks in advance.

**Comment by jcoupey** [comment]
Once the TSP is solved, the `-g` flag basically triggers a viaroute request to OSRM with the ordered locations. The mentioned assertion prevents the execution to go on when the json response of this viaroute query doesn't contain the required key (used to retrieve timing and distance information).

Try to track the corresponding request in osrm-routed logs and see if the 'route_summary' key is present when used in a browser or with curl.

Alternatively, you can try to spot unexpected values by checking the content of variables `query` and `json_response` appearing in https://github.com/jcoupey/vroom/blob/master/src/loaders/osrm_wrapper.h#L247-L253.

**Comment by KieCap** [comment]
Got it...

--max-viaroute-size needs to be set when running osrm-routed.

Thanks for the help. :)

**Comment by jcoupey** [comment]
Oh yes, didn't spot you mentioned the `--max-matching-size` and not the `--max-viaroute-size` parameter.

Rather than just stopping with the assertion, we should display the error message from OSRM to make it clear what went wrong. This will have to wait a little since all status codes and messages are bound to change in the new server API as of OSRM v5.
