### ISSUE TITLE
Error: incorrect "DIMENSION" key.

### ISSUE THREAD

**Issue by frodrigo** [jcoupey/vroom#6]
Code check DIMENSION is 2, but the as TSPLIB spec write: "Dimension is the numbers of nodes"
http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/DOC.PS

**Comment by jcoupey** [comment]
If you mean the check at:

https://github.com/jcoupey/vroom/blob/master/src/loaders/tsplib_loader.h#L112

its purpose is to ensure there has been a correct match for the regex used to retrieve the dimension.

If you get this error, can you please post the associated file, or link to it?

**Comment by frodrigo** [comment]
Oh, yes, I read the code too quickly. Bu by removing it's the only way for me to run on TSPLIB file.

**Comment by frodrigo** [comment]
It's issue is a mistake of command lie arg from me.
