### ISSUE TITLE
Use of std::cerr

### ISSUE THREAD

**Issue by frodrigo** [jcoupey/vroom#9]
Use of `std::cerr` in place of `std::cout` when the ouput is about error or info in the normal process.
Goal: have only expected result on cout. json to cout, into and error to cerr.

**Comment by jcoupey** [comment]
This makes definitely sense when errors occur and exceptions are raised. 

In a normal execution you already have two options to avoid mixing the info output with the json solution:
* don't use the `-v` flag to get only the json solution on cout;
* use the `-o` option to write the solution to a file, whatever goes on cout.
